:twitter: &default_twitter
  :consumer_key: Ckun6DMN0HxS3RkvHRTj3w
  :consumer_secret: ExUZI709psLbA2kmpHtSu9Pl9mCfxw9trZgg4Avazg
  :access_token: 65903555-VPpwAqLGZzSIJVZk8ShPgiz2P8OvEfcHoNx16PUsz
  :access_secret: xYGDX0yoJZVQcCTUyI48VhPn3RsahvHvr7i8qZf18


development:
  :twitter:
    <<: *default_twitter

test:
  :twitter:
    <<: *default_twitter

staging:
  :twitter:
    <<: *default_twitter
