:twitter: &default_twitter
  :login: vurlme_test
  :password: passwordz

development:
  :twitter:
    <<: *default_twitter

test:
  :twitter:
    <<: *default_twitter

staging:
  :twitter:
    <<: *default_twitter
